
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - Dirty deeds done dirt/01 DIRTY DEEDS DONE DIRT.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 DIRTY DEEDS DONE DIRT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - High voltage/05 - TNT.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - TNT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - High voltage/06 - Can I Sit Next To You Girl.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Can I Sit Next To You Girl.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - High voltage/09 - High Voltage.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 - High Voltage.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1977 - Let there be rock/02 DOG EAT DOG.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 DOG EAT DOG.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1977 - Let there be rock/08 WHOLE LOTTA ROSIE.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 WHOLE LOTTA ROSIE.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1979 - Highway to hell/01 HIGHWAY TO HELL.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 HIGHWAY TO HELL.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1979 - Highway to hell/08 IF YOU WANT BLOOD.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 IF YOU WANT BLOOD.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/01 HELLS BELLS.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 HELLS BELLS.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/02 SHOOT TO THRILL.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 SHOOT TO THRILL.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/03 WHAT DO YOU DO FOR MON.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 WHAT DO YOU DO FOR MON.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/04 GIVEN THE DOG A BONE.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 GIVEN THE DOG A BONE.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/05 LET ME PUT MY LOVE INT.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 LET ME PUT MY LOVE INT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/06 BACK IN BLACK.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 BACK IN BLACK.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/07 YOU SHOOK ME ALL NIGHT.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 YOU SHOOK ME ALL NIGHT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1984 - 74 Jailbreak/01 JAILBREAK.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 JAILBREAK.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1997 - Volts/02 TOUCH TOO MUCH.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 TOUCH TOO MUCH.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1997 - Volts/03 IF YOU WANT BLOOD YOU.MP3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 IF YOU WANT BLOOD YOU.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/The Razors Edge/01 - AC-DC - Thunderstruck.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - AC-DC - Thunderstruck.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/The Razors Edge/04 - AC-DC - The Razors Edge.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - AC-DC - The Razors Edge.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/The Razors Edge/07 - AC-DC - Are You Ready.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 - AC-DC - Are You Ready.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1979 Accept/03 Seawinds.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 Seawinds.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1979 Accept/07 Glad to Be Alone.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 Glad to Be Alone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1980 I'm a Rebel/01 I'm a Rebel.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 I'm a Rebel.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1980 I'm a Rebel/07 The King.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 The King.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/03 - Run If You Can.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Run If You Can.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/04 - Can't Stand The Night.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Can't Stand The Night.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/05 - Son Of A Bitch.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Son Of A Bitch.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/06 - Burning.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Burning.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/08 - Midnight Highway.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Midnight Highway.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/09 - Breaking Up Again.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 - Breaking Up Again.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1982 Restless and Wild/01 Fast as a Shark.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 Fast as a Shark.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1982 Restless and Wild/02 Restless and Wild.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 Restless and Wild.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1982 Restless and Wild/10 Princess of the Dawn.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 Princess of the Dawn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1983 Balls to the Wall/01 Balls to the Wall.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 Balls to the Wall.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1983 Balls to the Wall/02 London Leatherboys.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 London Leatherboys.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1983 Balls to the Wall/06 Love Child.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 Love Child.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1983 Balls to the Wall/08 Losers and Winners.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 Losers and Winners.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1983 Balls to the Wall/09 Guardian of the Night.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 Guardian of the Night.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1985 Metal Heart/01 Metal Heart.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 Metal Heart.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1985 Metal Heart/02 Midnight Mover.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 Midnight Mover.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1985 Metal Heart/10 Bound to Fail.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 Bound to Fail.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1986 Russian Roulette/03 Russian Roulette.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 Russian Roulette.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1986 Russian Roulette/04 It's Hard to Find a Way.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 It's Hard to Find a Way.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1989 Eat the Heat/09 Mistreated.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 Mistreated.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1994 Death Row/14 Drifting Away.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/14 Drifting Away.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/1989 - Alice In Hell/01 – Crystal Ann.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 – Crystal Ann.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/1989 - Alice In Hell/02 – Alison Hell.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 – Alison Hell.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/1993 - Set The World On Fire/05 – Phoenix Rising.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 – Phoenix Rising.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/1994 - King Of The Kill/10 - In The Blood.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 - In The Blood.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/2004 - All For You/08 - Holding On.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Holding On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(01) [Dream Theater] Pull Me Under.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(01) [Dream Theater] Pull Me Under.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(02) [Dream Theater] Another Day.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(02) [Dream Theater] Another Day.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(03) [Dream Theater] Take The Time.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(03) [Dream Theater] Take The Time.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(04) [Dream Theater] Surrounded.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(04) [Dream Theater] Surrounded.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(05) [Dream Theater] Metropolis-Part I- The Miracle And The Sleeper.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(05) [Dream Theater] Metropolis-Part I- The Miracle And The Sleeper.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(06) [Dream Theater] Under A Glass Moon.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(06) [Dream Theater] Under A Glass Moon.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(07) [Dream Theater] Wait For Sleep.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(07) [Dream Theater] Wait For Sleep.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(08) [Dream Theater] Learning To Live.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/(08) [Dream Theater] Learning To Live.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1987 - Keeper Of The Seven Keys Part I/Helloween - Keeper Of The Seven Keys Part I - 05 - A Tale That Wasn't Right.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part I - 05 - A Tale That Wasn't Right.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1987 - Keeper Of The Seven Keys Part I/Helloween - Keeper Of The Seven Keys Part I - 07 - Halloween.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part I - 07 - Halloween.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1988 - Keeper Of The Seven Keys Part II/Helloween - Keeper Of The Seven Keys Part II - 08 - I Want Out.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part II - 08 - I Want Out.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/2003 - Rabbit Don't Come Easy/Helloween - Rabbit Don't Come Easy - 11 - Listen To The Flies.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween - Rabbit Don't Come Easy - 11 - Listen To The Flies.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.01 - We Burn.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.01 - We Burn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.05 - Forever And One (Neverland).flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.05 - Forever And One (Neverland).ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.11 - If I Knew.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.11 - If I Knew.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/01 - Be Quick Or Be Dead.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Be Quick Or Be Dead.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/03 - Afraid To Shoot Strangers.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Afraid To Shoot Strangers.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/04 - Fear Is The Key.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Fear Is The Key.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/06 - Wasting Love.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Wasting Love.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/10 - Judas Be My Guide.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 - Judas Be My Guide.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/12 - Fear Of The Dark.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/12 - Fear Of The Dark.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/01 - Invaders.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Invaders.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/02 - Children Of The Damned.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Children Of The Damned.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/05 - The Number Of The Beast.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - The Number Of The Beast.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/06 - Run To The Hills.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Run To The Hills.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/08 - Hallowed Be Thy Name.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Hallowed Be Thy Name.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/01 The Wicker Man.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 The Wicker Man.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/02 Ghost Of The Navigator.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 Ghost Of The Navigator.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/04 Blood Brothers.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 Blood Brothers.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/06 Dream Of Mirrors.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 Dream Of Mirrors.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/10 The Thin Line Between Love And Hate.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 The Thin Line Between Love And Hate.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/07 New Frontier.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 New Frontier.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/11 Journeyman.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/11 Journeyman.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/04 Phantom Of The Opera.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 Phantom Of The Opera.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/05 Transylvania.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 Transylvania.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/07 Charlotte The Harlot.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 Charlotte The Harlot.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Killers/02 Wrathchild.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 Wrathchild.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Killers/03 Murders In The Rue Morgue.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 Murders In The Rue Morgue.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/03 No Prayer For The Dying.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 No Prayer For The Dying.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/09 Bring Your Daughter... To The Slaughter.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 Bring Your Daughter... To The Slaughter.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/10 Mother Russia.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 Mother Russia.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Piece Of Mind/05 The Trooper.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 The Trooper.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/01 Aces High.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 Aces High.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/02 2 Minutes To Midnight.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 2 Minutes To Midnight.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/04 Flash Of The Blade.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 Flash Of The Blade.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/06 Back In The Village.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 Back In The Village.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/01 Moonchild.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 Moonchild.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/03 Can I Play With Madness.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 Can I Play With Madness.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/04 The Evil That Men Do.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 The Evil That Men Do.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/05 Seventh Son of a Seventh Son.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 Seventh Son of a Seventh Son.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/06 The Prophecy.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 The Prophecy.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/07 The Clairvoyant.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 The Clairvoyant.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Somewhere In Time/02 Wasted Years.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 Wasted Years.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Somewhere In Time/05 The Loneliness Of The Long Distance Runner.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 The Loneliness Of The Long Distance Runner.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_The X Factor/10 2 A.M..flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 2 A.M..ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Virtual XI/05 When Two Worlds Collide.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 When Two Worlds Collide.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1974 - Rocka Rolla - Sad Wings of Destiny  (Remastered 2006)/01 - Victim of Changes.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Victim of Changes.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1974 - Rocka Rolla - Sad Wings of Destiny  (Remastered 2006)/02 - Rocka Rolla.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Rocka Rolla.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1974 - Rocka Rolla - Sad Wings of Destiny  (Remastered 2006)/02 - The Ripper.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - The Ripper.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1974 - Rocka Rolla - Sad Wings of Destiny  (Remastered 2006)/06 - Tyrant.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Tyrant.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1977 - Sin After Sin/01 - Sinner.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Sinner.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1977 - Sin After Sin/02 - Diamonds and Rust.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Diamonds and Rust.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1977 - Sin After Sin/03 - Starbreaker.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Starbreaker.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1977 - Sin After Sin/05 - Let Us Prey - Call For the Priest.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Let Us Prey - Call For the Priest.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Killing Machine/04 - Hell Bent For Leather.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Hell Bent For Leather.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Killing Machine/08 - Killing Machine.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Killing Machine.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Killing Machine/10 - Before The Dawn.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 - Before The Dawn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/01 - Exciter.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Exciter.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/03 - Better By You, Better Than Me.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Better By You, Better Than Me.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/04 - Stained Class.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Stained Class.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/05 - Invader.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Invader.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/08 - Beyond the Realms of Death.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Beyond the Realms of Death.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/11 - Better By You, Better Than Me (live).flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/11 - Better By You, Better Than Me (live).ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/01 - Rapid Fire.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Rapid Fire.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/02 - Metal Gods.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Metal Gods.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/03 - Breaking The Law.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Breaking The Law.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/04 - Grinder.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Grinder.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/05 - United.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - United.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/06 - You Don't Have To Be Old To Be Wise.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - You Don't Have To Be Old To Be Wise.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/07 - Living After Midnight.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 - Living After Midnight.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/08 - The Rage.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - The Rage.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1981 - Point of Entry/01 - Heading Out to the Highway.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Heading Out to the Highway.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1982 - Screaming For Vengeance/01 - The Hellion.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - The Hellion.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1982 - Screaming For Vengeance/02 - Electric Eye.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Electric Eye.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1982 - Screaming For Vengeance/04 - Bloodstone.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Bloodstone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1982 - Screaming For Vengeance/07 - Screaming For Vengeance.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 - Screaming For Vengeance.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1982 - Screaming For Vengeance/08 - You've Got Another Thing Comin'.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - You've Got Another Thing Comin'.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/01 - Freewheel Burning.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Freewheel Burning.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/02 - Jawbreaker.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Jawbreaker.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/04 - The Sentinel.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - The Sentinel.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/05 - Love Bites.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Love Bites.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1988 - Ram It Down/01 - Ram It Down.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Ram It Down.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/01 - Painkiller.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Painkiller.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/02 - Hell Patrol.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Hell Patrol.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/04 - Leather Rebel.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Leather Rebel.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/05 - Metal Meltdown.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Metal Meltdown.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/06 - Night Crawler.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/06 - Night Crawler.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/08 - A Touch Of Evil.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - A Touch Of Evil.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/10 - One Shot At Glory.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/10 - One Shot At Glory.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/03 The Gods Made Heavy Metal.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 The Gods Made Heavy Metal.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/04 Courage.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 Courage.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/05 Number 1.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 Number 1.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/07 King.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 King.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/08 Today Is a Good Day to Die.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 Today Is a Good Day to Die.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/09 My Spirit Lives On.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 My Spirit Lives On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Battle Hymns (1982) {Original} [EAC - Lame V0]/08 - Battle Hymn.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Battle Hymn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Fighting The World (1987) {Original} [EAC - Lame V0]/01 - Fighting The World.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Fighting The World.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Fighting The World (1987) {Original} [EAC - Lame V0]/03 - Carry On.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Carry On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Fighting The World (1987) {Original} [EAC - Lame V0]/08 - Master Of Revenge.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Master Of Revenge.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Kings Of Metal (1988) {Original} [EAC - Lame V0]/08 - Hail And Kill.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Hail And Kill.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - The Triumph Of Steel (1992) [EAC - Lame V0]/01 - Achilles, Agony And Ecstasy In Eight Parts.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Achilles, Agony And Ecstasy In Eight Parts.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - The Triumph Of Steel (1992) [EAC - Lame V0]/02 - Metal Warriors.mp3" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Metal Warriors.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/01 - Metallica - Hit The Lights.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Metallica - Hit The Lights.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/02 - Metallica - The Four Horsemen.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Metallica - The Four Horsemen.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/03 - Metallica - Motorbreath.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Metallica - Motorbreath.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/05 - Metallica - (Anesthesia)--Pulling Teeth.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/05 - Metallica - (Anesthesia)--Pulling Teeth.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/08 - Metallica - No Remorse.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Metallica - No Remorse.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/09 - Metallica - Seek & Destroy.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/09 - Metallica - Seek & Destroy.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/01 - Metallica - Fight Fire With Fire.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Metallica - Fight Fire With Fire.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/02 - Metallica - Ride The Lightning.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Metallica - Ride The Lightning.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/03 - Metallica - For Whom The Bell Tolls.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Metallica - For Whom The Bell Tolls.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/04 - Metallica - Fade To Black.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Metallica - Fade To Black.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/07 - Metallica - Creeping Death.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/07 - Metallica - Creeping Death.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/08 - Metallica - The Call Of Ktulu (Instrumental).flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/08 - Metallica - The Call Of Ktulu (Instrumental).ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/01 - Metallica - Battery.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/01 - Metallica - Battery.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/02 - Metallica - Master Of Puppets.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/02 - Metallica - Master Of Puppets.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/03 - Metallica - The Thing That Should Not Be.flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/03 - Metallica - The Thing That Should Not Be.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/04 - Metallica - Welcome Home (Sanitarium).flac" -acodec libvorbis -ab 128k "/mnt/music/music/rock/04 - Metallica - Welcome Home (Sanitarium).ogg"
