ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - High voltage/06 - Can I Sit Next To You Girl.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Can I Sit Next To You Girl.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1976 - High voltage/09 - High Voltage.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - High Voltage.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1977 - Let there be rock/08 WHOLE LOTTA ROSIE.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 WHOLE LOTTA ROSIE.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1979 - Highway to hell/01 HIGHWAY TO HELL.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 HIGHWAY TO HELL.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1979 - Highway to hell/08 IF YOU WANT BLOOD.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 IF YOU WANT BLOOD.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/01 HELLS BELLS.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 HELLS BELLS.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/03 WHAT DO YOU DO FOR MON.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 WHAT DO YOU DO FOR MON.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/05 LET ME PUT MY LOVE INT.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 LET ME PUT MY LOVE INT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/06 BACK IN BLACK.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 BACK IN BLACK.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/ACDC - 1980 - Back in Black/07 YOU SHOOK ME ALL NIGHT.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 YOU SHOOK ME ALL NIGHT.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/The Razors Edge/01 - AC-DC - Thunderstruck.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - AC-DC - Thunderstruck.ogg"
ffmpeg -i "/mnt/music/music/rocks/ACDC/The Razors Edge/07 - AC-DC - Are You Ready.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - AC-DC - Are You Ready.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1979 Accept/07 Glad to Be Alone.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 Glad to Be Alone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1980 I'm a Rebel/01 I'm a Rebel.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 I'm a Rebel.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1980 I'm a Rebel/07 The King.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 The King.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/03 - Run If You Can.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Run If You Can.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/04 - Can't Stand The Night.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Can't Stand The Night.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/05 - Son Of A Bitch.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Son Of A Bitch.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/08 - Midnight Highway.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Midnight Highway.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1981 - Breaker [Original]/09 - Breaking Up Again.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - Breaking Up Again.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1982 Restless and Wild/01 Fast as a Shark.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Fast as a Shark.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1982 Restless and Wild/10 Princess of the Dawn.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 Princess of the Dawn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1985 Metal Heart/01 Metal Heart.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Metal Heart.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1985 Metal Heart/02 Midnight Mover.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Midnight Mover.ogg"
ffmpeg -i "/mnt/music/music/rocks/Accept/1986 Russian Roulette/03 Russian Roulette.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 Russian Roulette.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/1993 - Set The World On Fire/05 – Phoenix Rising.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 – Phoenix Rising.ogg"
ffmpeg -i "/mnt/music/music/rocks/Annihilator/2004 - All For You/08 - Holding On.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Holding On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(01) [Dream Theater] Pull Me Under.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(01) [Dream Theater] Pull Me Under.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(02) [Dream Theater] Another Day.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(02) [Dream Theater] Another Day.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(03) [Dream Theater] Take The Time.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(03) [Dream Theater] Take The Time.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(04) [Dream Theater] Surrounded.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(04) [Dream Theater] Surrounded.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(05) [Dream Theater] Metropolis-Part I- The Miracle And The Sleeper.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(05) [Dream Theater] Metropolis-Part I- The Miracle And The Sleeper.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(06) [Dream Theater] Under A Glass Moon.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(06) [Dream Theater] Under A Glass Moon.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(07) [Dream Theater] Wait For Sleep.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(07) [Dream Theater] Wait For Sleep.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/1992-Images And Words/(08) [Dream Theater] Learning To Live.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(08) [Dream Theater] Learning To Live.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1987 - Keeper Of The Seven Keys Part I/Helloween - Keeper Of The Seven Keys Part I - 05 - A Tale That Wasn't Right.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part I - 05 - A Tale That Wasn't Right.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1987 - Keeper Of The Seven Keys Part I/Helloween - Keeper Of The Seven Keys Part I - 07 - Halloween.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part I - 07 - Halloween.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/1988 - Keeper Of The Seven Keys Part II/Helloween - Keeper Of The Seven Keys Part II - 08 - I Want Out.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween - Keeper Of The Seven Keys Part II - 08 - I Want Out.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.01 - We Burn.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.01 - We Burn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.05 - Forever And One (Neverland).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.05 - Forever And One (Neverland).ogg"
ffmpeg -i "/mnt/music/music/rocks/Helloween/the time of the oath/Helloween.The Time Of The Oath.2eph.11 - If I Knew.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Helloween.The Time Of The Oath.2eph.11 - If I Knew.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/01 - Be Quick Or Be Dead.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Be Quick Or Be Dead.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/03 - Afraid To Shoot Strangers.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Afraid To Shoot Strangers.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/04 - Fear Is The Key.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Fear Is The Key.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/06 - Wasting Love.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Wasting Love.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - Fear Of The Dark (Remastered) - FLAC - HellraiserRG/12 - Fear Of The Dark.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/12 - Fear Of The Dark.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/01 - Invaders.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Invaders.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/02 - Children Of The Damned.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Children Of The Damned.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/05 - The Number Of The Beast.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - The Number Of The Beast.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/06 - Run To The Hills.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Run To The Hills.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden - The Number Of The Beast - FLAC - HellraiserRG/08 - Hallowed Be Thy Name.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Hallowed Be Thy Name.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/01 The Wicker Man.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 The Wicker Man.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/02 Ghost Of The Navigator.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Ghost Of The Navigator.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/04 Blood Brothers.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Blood Brothers.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Brave New World/10 The Thin Line Between Love And Hate.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 The Thin Line Between Love And Hate.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/07 New Frontier.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 New Frontier.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/11 Journeyman.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/11 Journeyman.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/04 Phantom Of The Opera.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Phantom Of The Opera.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/05 Transylvania.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Transylvania.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Iron Maiden/07 Charlotte The Harlot.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 Charlotte The Harlot.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Killers/02 Wrathchild.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Wrathchild.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Killers/03 Murders In The Rue Morgue.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 Murders In The Rue Morgue.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/03 No Prayer For The Dying.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 No Prayer For The Dying.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/09 Bring Your Daughter... To The Slaughter.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 Bring Your Daughter... To The Slaughter.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_No Prayer For The Dying/10 Mother Russia.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 Mother Russia.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Piece Of Mind/05 The Trooper.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 The Trooper.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/01 Aces High.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Aces High.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/02 2 Minutes To Midnight.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 2 Minutes To Midnight.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/04 Flash Of The Blade.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Flash Of The Blade.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Powerslave/06 Back In The Village.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 Back In The Village.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/01 Moonchild.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Moonchild.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/03 Can I Play With Madness.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 Can I Play With Madness.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/04 The Evil That Men Do.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 The Evil That Men Do.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/05 Seventh Son of a Seventh Son.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Seventh Son of a Seventh Son.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/06 The Prophecy.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 The Prophecy.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Seventh Son Of A Seventh Son/07 The Clairvoyant.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 The Clairvoyant.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Somewhere In Time/02 Wasted Years.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Wasted Years.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Somewhere In Time/05 The Loneliness Of The Long Distance Runner.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 The Loneliness Of The Long Distance Runner.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_The X Factor/10 2 A.M..flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 2 A.M..ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Virtual XI/05 When Two Worlds Collide.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 When Two Worlds Collide.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1974 - Rocka Rolla - Sad Wings of Destiny  (Remastered 2006)/02 - Rocka Rolla.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Rocka Rolla.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Killing Machine/10 - Before The Dawn.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 - Before The Dawn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/01 - Exciter.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Exciter.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1978 - Stained Class/08 - Beyond the Realms of Death.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Beyond the Realms of Death.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/03 - Breaking The Law.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Breaking The Law.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1980 - British Steel/07 - Living After Midnight.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Living After Midnight.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/01 - Freewheel Burning.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Freewheel Burning.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/02 - Jawbreaker.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Jawbreaker.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/1984 - Defenders Of The Faith/05 - Love Bites.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Love Bites.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/01 - Painkiller.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Painkiller.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/04 - Leather Rebel.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Leather Rebel.ogg"
ffmpeg -i "/mnt/music/music/rocks/Judas Priest -  The Remasters/Judas Priest (1990) Painkiller (2001 Remastered Edition)/06 - Night Crawler.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Night Crawler.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/04 Courage.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Courage.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/05 Number 1.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Number 1.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/07 King.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 King.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/08 Today Is a Good Day to Die.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 Today Is a Good Day to Die.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/MANOWAR (USA) - Louder Than Hell [1996][heavy metal][mp3@256kbs]/09 My Spirit Lives On.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 My Spirit Lives On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Fighting The World (1987) {Original} [EAC - Lame V0]/01 - Fighting The World.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Fighting The World.ogg"
ffmpeg -i "/mnt/music/music/rocks/Manowar/Manowar - Fighting The World (1987) {Original} [EAC - Lame V0]/03 - Carry On.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Carry On.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/01 - Metallica - Hit The Lights.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Metallica - Hit The Lights.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/05 - Metallica - (Anesthesia)--Pulling Teeth.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Metallica - (Anesthesia)--Pulling Teeth.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1983.Kill 'Em All/09 - Metallica - Seek & Destroy.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - Metallica - Seek & Destroy.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/01 - Metallica - Fight Fire With Fire.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Metallica - Fight Fire With Fire.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/02 - Metallica - Ride The Lightning.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Metallica - Ride The Lightning.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/03 - Metallica - For Whom The Bell Tolls.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Metallica - For Whom The Bell Tolls.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/04 - Metallica - Fade To Black.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Metallica - Fade To Black.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/07 - Metallica - Creeping Death.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Metallica - Creeping Death.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1984.Ride The Lightning/08 - Metallica - The Call Of Ktulu (Instrumental).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Metallica - The Call Of Ktulu (Instrumental).ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/01 - Metallica - Battery.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Metallica - Battery.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/02 - Metallica - Master Of Puppets.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Metallica - Master Of Puppets.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/03 - Metallica - The Thing That Should Not Be.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Metallica - The Thing That Should Not Be.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/04 - Metallica - Welcome Home (Sanitarium).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Metallica - Welcome Home (Sanitarium).ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/05 - Metallica - Disposable Heroes.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Metallica - Disposable Heroes.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1986.Master of Puppets/07 - Metallica - Orion (Instrumental).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Metallica - Orion (Instrumental).ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/01 - Metallica - Blackened.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Metallica - Blackened.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/02 - Metallica - ...And Justice For All.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Metallica - ...And Justice For All.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/03 - Metallica - Eye Of The Beholder.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Metallica - Eye Of The Beholder.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/04 - Metallica - One.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Metallica - One.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/06 - Metallica - Harvester Of Sorrow.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Metallica - Harvester Of Sorrow.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1988.And Justice for All/08 - Metallica - To Live Is To Die  (Instrumental).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Metallica - To Live Is To Die  (Instrumental).ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/01 - Metallica - Enter Sandman.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Metallica - Enter Sandman.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/02 - Metallica - Sad But True.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Metallica - Sad But True.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/04 - Metallica - The Unforgiven.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Metallica - The Unforgiven.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/05 - Metallica - Wherever I May Roam.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Metallica - Wherever I May Roam.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/08 - Metallica - Nothing Else Matters.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Metallica - Nothing Else Matters.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/09 - Metallica - Of Wolf And Man.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - Metallica - Of Wolf And Man.ogg"
ffmpeg -i "/mnt/music/music/rocks/Metallica/1991.Metallica ( Black Album )/10 - Metallica - The God That Failed.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 - Metallica - The God That Failed.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1988 - Under The Influence/03 - Hello From The Gutter.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Hello From The Gutter.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1989 - The Years Of Decay/03 - I Hate.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - I Hate.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1991 - Horrorscope/11 - Solitude.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/11 - Solitude.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1994 - W.F.O/08 - R.I.P. (Undone).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - R.I.P. (Undone).ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1994 - W.F.O/10 - Bastard Nation.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 - Bastard Nation.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1994 - W.F.O/11 - Gasoline Dream.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/11 - Gasoline Dream.ogg"
ffmpeg -i "/mnt/music/music/rocks/Overkill/1999 - Coverkill/04 - Changes.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Changes.ogg"
ffmpeg -i "/mnt/music/music/rocks/Ozzy Osbourne/Ozzy Osbourne - Blizzard Of Ozz (2002 Re-Master)/02 - Crazy Train.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Crazy Train.ogg"
ffmpeg -i "/mnt/music/music/rocks/Ozzy Osbourne/Ozzy Osbourne - Blizzard Of Ozz (2002 Re-Master)/03 - Goodbye To Romance.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Goodbye To Romance.ogg"
ffmpeg -i "/mnt/music/music/rocks/Ozzy Osbourne/Ozzy Osbourne - Blizzard Of Ozz (2002 Re-Master)/06 - Mr. Crowley.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Mr. Crowley.ogg"
ffmpeg -i "/mnt/music/music/rocks/Ozzy Osbourne/Ozzy Osbourne - Blizzard Of Ozz (2002 Re-Master)/08 - Revelation (Mother Earth).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Revelation (Mother Earth).ogg"
ffmpeg -i "/mnt/music/music/rocks/Ozzy Osbourne/Ozzy Osbourne - No More Tears/03 - Mama, I'm Coming Home.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Mama, I'm Coming Home.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Animals/01 - Pigs on the Wing (Part 1).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Pigs on the Wing (Part 1).ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Meddle/Pink Floyd - Meddle (Original Master Recording) - 06 Echoes .flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd - Meddle (Original Master Recording) - 06 Echoes .ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - Atom Heart Mother/01 Atom Heart Mother Suite.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Atom Heart Mother Suite.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - Atom Heart Mother/02 If.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 If.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - Atom Heart Mother/03 Summer '68.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 Summer '68.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - Atom Heart Mother/05 Alan's Psychedelic Breakfast.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Alan's Psychedelic Breakfast.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - More/05 Green Is The Colour.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Green Is The Colour.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - Obscured By Clouds/Pink Floyd-Obscured By Clouds-01-Obscured By Clouds.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Obscured By Clouds-01-Obscured By Clouds.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The dark side of the moon/Pink Floyd-Dark Side Of The Moon-03-Time.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Dark Side Of The Moon-03-Time.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The dark side of the moon/Pink Floyd-Dark Side Of The Moon-05-Money.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Dark Side Of The Moon-05-Money.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The dark side of the moon/Pink Floyd-Dark Side Of The Moon-06-Us And Them.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Dark Side Of The Moon-06-Us And Them.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The division bell/Pink Floyd-The Division Bell-11-High Hopes.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Division Bell-11-High Hopes.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 1)/Pink Floyd-The Wall  (disc 1)-06-Mother.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall  (disc 1)-06-Mother.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 1)/Pink Floyd-The Wall  (disc 1)-07-Goodbye Blue Sky.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall  (disc 1)-07-Goodbye Blue Sky.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 1)/Pink Floyd-The Wall  (disc 1)-12-Another Brick in the Wall - part 3.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall  (disc 1)-12-Another Brick in the Wall - part 3.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 1)/Pink Floyd-The Wall  (disc 1)-13-Goodbye Cruel World.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall  (disc 1)-13-Goodbye Cruel World.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 2)/Pink Floyd-The Wall (disc 2)-01-Hey You!.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall (disc 2)-01-Hey You!.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Pink Floyd - The wall (disc 2)/Pink Floyd-The Wall (disc 2)-06-Comfortably Numb.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-The Wall (disc 2)-06-Comfortably Numb.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Wish you were here/Pink Floyd-Wish You Were Here-01-Shine On You Crazy Diamond (Part I-IV).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Wish You Were Here-01-Shine On You Crazy Diamond (Part I-IV).ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Wish you were here/Pink Floyd-Wish You Were Here-02-Welcome to the Machine.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Wish You Were Here-02-Welcome to the Machine.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Wish you were here/Pink Floyd-Wish You Were Here-05-Shine On You Crazy Diamond (Part V-IX).flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Wish You Were Here-05-Shine On You Crazy Diamond (Part V-IX).ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/1976-No Heavy Petting/04 - Belladonna.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Belladonna.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/1977-Lights Out/04 - Lights Out.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Lights Out.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/1978-Obsession/01 - Only You Can Rock Me.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Only You Can Rock Me.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/UFO - Phenomenon (Re-Mastered 1994) FLAC/UFO - 03 - Doctor Doctor.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/UFO - 03 - Doctor Doctor.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/UFO - Phenomenon (Re-Mastered 1994) FLAC/UFO - 04 - Space Child.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/UFO - 04 - Space Child.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/UFO - Phenomenon (Re-Mastered 1994) FLAC/UFO - 05 - Rock Bottom.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/UFO - 05 - Rock Bottom.ogg"
ffmpeg -i "/mnt/music/music/rocks/UFO/UFO - Phenomenon (Re-Mastered 1994) FLAC/UFO - 09 - Lipstick Traces.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/UFO - 09 - Lipstick Traces.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/05 - LOVE HURTS.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - LOVE HURTS.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Before the winter - Stratovarius.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Before the winter - Stratovarius.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Can't fin my way - hardline.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Can't fin my way - hardline.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Carry on (Chris De Burgh).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Carry on (Chris De Burgh).ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Cats In The Cradle.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Cats In The Cradle.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Don't go (Nitro).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Don't go (Nitro).ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/I can't wait (Dirty Rhythm).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/I can't wait (Dirty Rhythm).ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/KuschelRock Vol.01 (CD2) - 04 - Chicago - Hard To Say I'm Sorry.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/KuschelRock Vol.01 (CD2) - 04 - Chicago - Hard To Say I'm Sorry.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/MSG__WHAT_HAPPENS_TO_ME.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/MSG__WHAT_HAPPENS_TO_ME.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Memory - Sevatage.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Memory - Sevatage.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Mozart and madness - Sevatage.MP3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Mozart and madness - Sevatage.ogg"
ffmpeg -i "/mnt/music/music/rocks/_Collection/Never again (Loudness).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Never again (Loudness).ogg"
ffmpeg -i "/mnt/music/music/rocks/collection/04-evanescence-lithium.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04-evanescence-lithium.ogg"
ffmpeg -i "/mnt/music/music/rocks/collection/08 - Stupid Girl.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Stupid Girl.ogg"
ffmpeg -i "/mnt/music/music/rocks/collection/Janine - Kingdom Come.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Janine - Kingdom Come.ogg"
ffmpeg -i "/mnt/music/music/rocks/collection/White Lion - When The Children Cry.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/White Lion - When The Children Cry.ogg"
ffmpeg -i "/mnt/music/music/rocks/100 Greatest Guitar Solos/Greatest Guitar Solos - 001 Led Zeppelin - Stairway to Heaven.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Greatest Guitar Solos - 001 Led Zeppelin - Stairway to Heaven.ogg"
ffmpeg -i "/mnt/music/music/rocks/100 Greatest Guitar Solos/Greatest Guitar Solos - 006 Guns N' Roses - November Rain.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Greatest Guitar Solos - 006 Guns N' Roses - November Rain.ogg"
ffmpeg -i "/mnt/music/music/rocks/100 Greatest Guitar Solos/Greatest Guitar Solos - 008 Eagles - Hotel California.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Greatest Guitar Solos - 008 Eagles - Hotel California.ogg"
ffmpeg -i "/mnt/music/music/rocks/Amorphis/2003 - Chapters (192)/01 - Alone.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Alone.ogg"
ffmpeg -i "/mnt/music/music/rocks/At the gate/1995 - Slaughter of the Soul/05 - Into The Dead Sky.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Into The Dead Sky.ogg"
ffmpeg -i "/mnt/music/music/rocks/Black Sabbath/02-Black Sabbath-1970-Paranoid/01-War Pigs-mw.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01-War Pigs-mw.ogg"
ffmpeg -i "/mnt/music/music/rocks/Black Sabbath/02-Black Sabbath-1970-Paranoid/02-Paranoid-mw.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02-Paranoid-mw.ogg"
ffmpeg -i "/mnt/music/music/rocks/Cynic/Cynic (USA) -Focus (1993) (Remastered-2004) [mp3@vbr] [Technical Progressive Death Metal]/01-cynic-veil_of_maya-rns.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01-cynic-veil_of_maya-rns.ogg"
ffmpeg -i "/mnt/music/music/rocks/Cynic/Cynic (USA) -Focus (1993) (Remastered-2004) [mp3@vbr] [Technical Progressive Death Metal]/07-cynic-textures-rns.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07-cynic-textures-rns.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/Projector/Dark Tranquility - Projector - 01 - Freecard.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - Projector - 01 - Freecard.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/The Gallery/Dark Tranquility - The Gallery - 08 - Lethe.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - The Gallery - 08 - Lethe.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/The Mind's I/Dark Tranquility - The Mind's I - 07 - Insanity's Crescendo.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - The Mind's I - 07 - Insanity's Crescendo.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/The Mind's I/Dark Tranquility - The Mind's I - 12 - The Mind's Eye.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - The Mind's I - 12 - The Mind's Eye.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1990 Spiritual Healing/06 - Low Life.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Low Life.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1991 Human/01 - Flattening of Emotions.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Flattening of Emotions.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1991 Human/05 - Lack of Comprehension.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Lack of Comprehension.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1991 Human/07 - Cosmic Sea.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Cosmic Sea.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1995 Symbolic/01 - 01-Symbolic.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - 01-Symbolic.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1995 Symbolic/03 - 03-Empty Words.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - 03-Empty Words.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1998 The Sound of Perseverance/06 - Voice of the Soul.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Voice of the Soul.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death/1998 The Sound of Perseverance/09 - Painkiller.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - Painkiller.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/1968 - Deep Purple - Shades Of Deep Purple/Deep Purple - Shades Of Deep Purple - 02 - Hush.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Deep Purple - Shades Of Deep Purple - 02 - Hush.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/1970 - Deep Purple - Deep Purple In Rock/Deep Purple - Deep Purple In Rock - 03 - Child In Time.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Deep Purple - Deep Purple In Rock - 03 - Child In Time.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/1973 - Deep Purple - Who Do We Think We Are/Deep Purple - Who Do We Think We Are - 01 - Woman From Tokio.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Deep Purple - Who Do We Think We Are - 01 - Woman From Tokio.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/Deep Purple - Machine Head (1972) [FLAC] {2010 Audio Fidelity 24 KT + Gold, AFZ 065} (Ltd. Numbered Ed.)/01 - Highway Star.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Highway Star.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/Deep Purple - Machine Head (1972) [FLAC] {2010 Audio Fidelity 24 KT + Gold, AFZ 065} (Ltd. Numbered Ed.)/05 - Smoke On The Water.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Smoke On The Water.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/Deep Purple - Machine Head (1972) [FLAC] {2010 Audio Fidelity 24 KT + Gold, AFZ 065} (Ltd. Numbered Ed.)/07 - Space Truckin'.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Space Truckin'.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deep Purple/Deep Purple_Burn/01 Burn.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Burn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dio/Holy Diver/08 - Rainbow In The Dark.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Rainbow In The Dark.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dire Straits/Dire Straits - Brothers In Arms (Re-Mastered 1996) EAC Flac Level 8/Dire Straits - 02 - Money For Nothing.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dire Straits - 02 - Money For Nothing.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dire Straits/Dire Straits - Brothers In Arms (Re-Mastered 1996) EAC Flac Level 8/Dire Straits - 03 - Walk Of Life.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dire Straits - 03 - Walk Of Life.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dire Straits/Dire Straits - Brothers In Arms (Re-Mastered 1996) EAC Flac Level 8/Dire Straits - 04 - Your Latest Trick.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dire Straits - 04 - Your Latest Trick.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dire Straits/Dire Straits - Brothers In Arms (Re-Mastered 1996) EAC Flac Level 8/Dire Straits - 09 - Brothers In Arms.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dire Straits - 09 - Brothers In Arms.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dire Straits/Dire Straits - Dire Straits/06. Sultans Of Swing.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06. Sultans Of Swing.ogg"
ffmpeg -i "/mnt/music/music/rocks/Exodus/1985 - Bonded By Blood (320)/04 - A Lesson In Violence.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - A Lesson In Violence.ogg"
ffmpeg -i "/mnt/music/music/rocks/Gun n Rose/03 Use Your Illusion I/03 Use Your Illusion I/04 Don't Cry.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Don't Cry.ogg"
ffmpeg -i "/mnt/music/music/rocks/Gun n Rose/Appetite for Destruction/09 Appetite for Destruction - 09 - Sweet Child o' Mine.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 Appetite for Destruction - 09 - Sweet Child o' Mine.ogg"
ffmpeg -i "/mnt/music/music/rocks/Gun n Rose/The Spaghetti Incident/Guns N' Roses - Since I Don't Have You.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Guns N' Roses - Since I Don't Have You.ogg"
ffmpeg -i "/mnt/music/music/rocks/HammerFall/Albums/(1997) Glory to the Brave (192 Kbps)/04-I Believe.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04-I Believe.ogg"
ffmpeg -i "/mnt/music/music/rocks/HammerFall/Albums/(1997) Glory to the Brave (192 Kbps)/09-Glory To The Brave.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09-Glory To The Brave.ogg"
ffmpeg -i "/mnt/music/music/rocks/HammerFall/Albums/(2002) Crimson Thunder (192 Kbps)/04 - Crimson Thunder.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Crimson Thunder.ogg"
ffmpeg -i "/mnt/music/music/rocks/Hypocrisy/2000 - Into The Abyss/Hypocrisy - Into The Abyss - 10 - Deathrow (no regrets).mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Hypocrisy - Into The Abyss - 10 - Deathrow (no regrets).ogg"
ffmpeg -i "/mnt/music/music/rocks/Iced Earth/Iced Earth - Iced Earth/06 - Solitude [Instrumental].Mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Solitude [Instrumental].ogg"
ffmpeg -i "/mnt/music/music/rocks/Iced Earth/Iced Earth - Iced Earth/08 - When the Night Falls.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - When the Night Falls.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/Come Clarity/06. Come Clarity.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06. Come Clarity.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/In Flames - Lunar Strain (1994) & Subterranean (1995)/In Flames - Lunar Strain & Subterranean - 02. Lunar Strain.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/In Flames - Lunar Strain & Subterranean - 02. Lunar Strain.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/In Flames - Lunar Strain (1994) & Subterranean (1995)/In Flames - Lunar Strain & Subterranean - 12. Everdying.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/In Flames - Lunar Strain & Subterranean - 12. Everdying.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/In Flames - Lunar Strain (1994) & Subterranean (1995)/In Flames - Lunar Strain & Subterranean - 14. Timeless.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/In Flames - Lunar Strain & Subterranean - 14. Timeless.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/Lunar Strain/13. Acoustic Piece.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/13. Acoustic Piece.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/The Jester Race  Black-Ash Inheritance/01. Moonshield.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01. Moonshield.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/The Jester Race  Black-Ash Inheritance/03. Artifacts of the Black Rain.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03. Artifacts of the Black Rain.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/The Jester Race  Black-Ash Inheritance/07. The Jester Race.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07. The Jester Race.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/The Jester Race  Black-Ash Inheritance/09. Wayfaerer.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09. Wayfaerer.ogg"
ffmpeg -i "/mnt/music/music/rocks/In Flames/The Jester Race  Black-Ash Inheritance/13. Acoustic Medley.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/13. Acoustic Medley.ogg"
ffmpeg -i "/mnt/music/music/rocks/Kingdom Come - Kingdom Come [1988] by Iommi/03 - What Love Can Be.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - What Love Can Be.ogg"
ffmpeg -i "/mnt/music/music/rocks/Kotipelto/(2002) Waiting For The Dawn/10 - Waiting For The Dawn - Waiting For The Dawn - Kotipelto.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 - Waiting For The Dawn - Waiting For The Dawn - Kotipelto.ogg"
ffmpeg -i "/mnt/music/music/rocks/Kotipelto/(2002) Waiting For The Dawn/12 - The Movement Of The Nile - Waiting For The Dawn - Kotipelto.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/12 - The Movement Of The Nile - Waiting For The Dawn - Kotipelto.ogg"
ffmpeg -i "/mnt/music/music/rocks/Lacuna Coil [MrGrimmz]/Lacuna Coil - Halflife (2000)/Lacuna Coil - Half Life - 05 - Stars.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Lacuna Coil - Half Life - 05 - Stars.ogg"
ffmpeg -i "/mnt/music/music/rocks/Lake of Tears/Lake Of Tears/1999 - Forever Autumn/01 - So Fell Autumn Rain.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - So Fell Autumn Rain.ogg"
ffmpeg -i "/mnt/music/music/rocks/Lake of Tears/Lake Of Tears/1999 - Forever Autumn/02 - Hold On Tight.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Hold On Tight.ogg"
ffmpeg -i "/mnt/music/music/rocks/Lake of Tears/Lake Of Tears/1999 - Forever Autumn/03 - Forever Autumn.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - Forever Autumn.ogg"
ffmpeg -i "/mnt/music/music/rocks/Led Zeppelin - Discography (MP3@320Kbps)/Led Zeppelin - Led Zeppelin II (1969) {1994 Remaster}/08 - Moby Dick.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Moby Dick.ogg"
ffmpeg -i "/mnt/music/music/rocks/Led Zeppelin - Discography (MP3@320Kbps)/Led Zeppelin - Led Zeppelin IV (1971) {1994 Remaster}/04 - Stairway To Heaven.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - Stairway To Heaven.ogg"
ffmpeg -i "/mnt/music/music/rocks/Megadeth - Discografia [www.heavytorrents.org]/[1990] Rust In Peace/02. Hangar 18.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02. Hangar 18.ogg"
ffmpeg -i "/mnt/music/music/rocks/Megadeth - Discografia [www.heavytorrents.org]/[1994] Youthanasia/04. A Tout Le Monde.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04. A Tout Le Monde.ogg"
ffmpeg -i "/mnt/music/music/rocks/Megadeth - Discografia [www.heavytorrents.org]/[1994] Youthanasia/08. Family Tree.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08. Family Tree.ogg"
ffmpeg -i "/mnt/music/music/rocks/Mercyful Fate/Mercyful Fate [1983] Melissa (25th Anniversary Reissue)/07. Melissa.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07. Melissa.ogg"
ffmpeg -i "/mnt/music/music/rocks/Mercyful Fate/Mercyful Fate [1984] Don't Break The Oath/01. A Dangerous Meeting.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01. A Dangerous Meeting.ogg"
ffmpeg -i "/mnt/music/music/rocks/Mercyful Fate/Mercyful Fate [1993] In The Shadows/09. Is That You, Melissa.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09. Is That You, Melissa.ogg"
ffmpeg -i "/mnt/music/music/rocks/Mercyful Fate/Mercyful Fate [1995] Time/01. Nightmare Be Thy Name.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01. Nightmare Be Thy Name.ogg"
ffmpeg -i "/mnt/music/music/rocks/Nile/2002 - In Their Darkened Shrines (320)/12 - In Their Darkened Shrines IV - Ruins.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/12 - In Their Darkened Shrines IV - Ruins.ogg"
ffmpeg -i "/mnt/music/music/rocks/Nirvana/Nirvana - 1991 - Nevermind/Nirvana - 01 - Smells Like Teen Spirit.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Nirvana - 01 - Smells Like Teen Spirit.ogg"
ffmpeg -i "/mnt/music/music/rocks/Nirvana/Nirvana - 1991 - Nevermind/Nirvana - 05 - Lithium.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Nirvana - 05 - Lithium.ogg"
ffmpeg -i "/mnt/music/music/rocks/Nirvana/Nirvana - 1994 - Unplugged in New York (1994)/Nirvana - 04 - The Man Who Sold The World.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Nirvana - 04 - The Man Who Sold The World.ogg"
ffmpeg -i "/mnt/music/music/rocks/Nirvana/Nirvana - 1994 - Unplugged in New York (1994)/Nirvana - 14 - Where Did You Sleep Last Night.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Nirvana - 14 - Where Did You Sleep Last Night.ogg"
ffmpeg -i "/mnt/music/music/rocks/Paradise lost/One Second/Paradise Lost-One Second-01-One Second.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Paradise Lost-One Second-01-One Second.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/08 A Night at the Opera (1993) (MFSL Gold)/11 - Bohemian Rhapsody.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/11 - Bohemian Rhapsody.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/08 A Night at the Opera (1993) (MFSL Gold)/12 - God Save The Queen.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/12 - God Save The Queen.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/12 The Works (1984)/03 - It's A Hard Life.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 - It's A Hard Life.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/12 The Works (1984)/06 - I Want To Break Free.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - I Want To Break Free.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/13 A Kind Of Magic (1986)/02 - A Kind Of Magic.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - A Kind Of Magic.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/16 The Miracle (1989)/04 - I Want It All.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 - I Want It All.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/18 Innuendo (1991)/01 - Innuendo.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Innuendo.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/21 Made In Heaven (1995)/02 - Made In Heaven.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Made In Heaven.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queen discography (MP3@320Kbps)/Queen discography (MP3@320Kbps)/21 Made In Heaven (1995)/07 - Heaven For Everyone.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Heaven For Everyone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Queensryche/queensryche - 1994 - promised land (remastered)/queensryche - 08 - lady jane.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/queensryche - 08 - lady jane.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rainbow - discography/1975 - Ritchie Blackmore's Rainbow/01 Rainbow - Man on the Silver Mountain.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Rainbow - Man on the Silver Mountain.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rainbow - discography/1975 - Ritchie Blackmore's Rainbow/04 Rainbow - Catch The Rainbow.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Rainbow - Catch The Rainbow.ogg"
ffmpeg -i "/mnt/music/music/rocks/Red Hot Chili Peppers-Discography/08 By the Way/01 By the Way.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 By the Way.ogg"
ffmpeg -i "/mnt/music/music/rocks/Red Hot Chili Peppers-Discography/08 By the Way/07 Can't Stop.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 Can't Stop.ogg"
ffmpeg -i "/mnt/music/music/rocks/Red Hot Chili Peppers-Discography/08 By the Way/13 On Mercury.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/13 On Mercury.ogg"
ffmpeg -i "/mnt/music/music/rocks/Red Hot Chili Peppers-Discography/08 By the Way/14 Minor Thing.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/14 Minor Thing.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rhapsody of Fire/Rhapsody -1999- Symphony of Enchanted Lands/02.-  Emerald Sword.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02.-  Emerald Sword.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rhapsody of Fire/Rhapsody -1999- Symphony of Enchanted Lands/03.-  Wisdom of the Kings.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03.-  Wisdom of the Kings.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rhapsody of Fire/Rhapsody -1999- Symphony of Enchanted Lands/04.-  Heroes of the Lost Valley.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04.-  Heroes of the Lost Valley.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rhapsody of Fire/Rhapsody -1999- Symphony of Enchanted Lands/07.-  Wings of Destiny.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07.-  Wings of Destiny.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1975 In Trance/02-In Trance.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02-In Trance.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1979 Lovedrive/03-Always Somewhere.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03-Always Somewhere.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1979 Lovedrive/08-Holiday.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08-Holiday.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1982 Blackout/09-When The Smoke Is Going Down.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09-When The Smoke Is Going Down.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1984 Love at first sting/09-Still Loving You.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09-Still Loving You.ogg"
ffmpeg -i "/mnt/music/music/rocks/Scorpions/1990 Crazy World/04-Wind Of Change.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04-Wind Of Change.ogg"
ffmpeg -i "/mnt/music/music/rocks/Sex Pistols/1977 - Never Mind the Bollocks/05 - God Save the Queen.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - God Save the Queen.ogg"
ffmpeg -i "/mnt/music/music/rocks/Sex Pistols/1980 - The Great Rock 'N' Roll Swindle/13. My Way.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/13. My Way.ogg"
ffmpeg -i "/mnt/music/music/rocks/Skid Row/Skid Row/05 - 18 And Life.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - 18 And Life.ogg"
ffmpeg -i "/mnt/music/music/rocks/Slayer/Season In The Abyss/10 Seasons In The Abyss.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/10 Seasons In The Abyss.ogg"
ffmpeg -i "/mnt/music/music/rocks/Soundgarden/Superunknown/07 - Black Hole Sun.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Black Hole Sun.ogg"
ffmpeg -i "/mnt/music/music/rocks/Stratovarious/Stratovarius - 1996 - Episode/12-Forever.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/12-Forever.ogg"
ffmpeg -i "/mnt/music/music/rocks/Testament/1987 - The Legacy/08 - Alone In The Dark.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08 - Alone In The Dark.ogg"
ffmpeg -i "/mnt/music/music/rocks/The Who - Discography (Mp3@320Kbps)/The Who - Discography (Mp3@320Kbps)/01. The Who Sings My Generation/06. My Generation.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06. My Generation.ogg"
ffmpeg -i "/mnt/music/music/rocks/The Who - Discography (Mp3@320Kbps)/The Who - Discography (Mp3@320Kbps)/02. A Quick One/19. Man With the Money.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/19. Man With the Money.ogg"
ffmpeg -i "/mnt/music/music/rocks/The Who - Discography (Mp3@320Kbps)/The Who - Discography (Mp3@320Kbps)/05. Who's Next/01. Baba O' Riley.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01. Baba O' Riley.ogg"
ffmpeg -i "/mnt/music/music/rocks/The Who - Discography (Mp3@320Kbps)/The Who - Discography (Mp3@320Kbps)/05. Who's Next/08. Behind Blue Eyes.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/08. Behind Blue Eyes.ogg"
ffmpeg -i "/mnt/music/music/rocks/The Who - Discography (Mp3@320Kbps)/The Who - Discography (Mp3@320Kbps)/05. Who's Next/09. Won't Get Fooled Again.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09. Won't Get Fooled Again.ogg"
ffmpeg -i "/mnt/music/music/rocks/Theory In Practice/Theory In Practice - 2002 - Colonizing The Sun 320 (nameless for STB)/01 - Colonizing the Sun.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Colonizing the Sun.ogg"
ffmpeg -i "/mnt/music/music/rocks/Theory In Practice/Theory In Practice - 2002 - Colonizing The Sun 320 (nameless for STB)/09 - This Town Ain't Big Enough for Both of Us.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - This Town Ain't Big Enough for Both of Us.ogg"
ffmpeg -i "/mnt/music/music/rocks/Tokio Hotel/Schrei/02 Durch den monsun.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Durch den monsun.ogg"
ffmpeg -i "/mnt/music/music/rocks/Van Halen - Discography @ 320/1982 Diver Down (320)/06 - (Oh) Pretty Woman.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - (Oh) Pretty Woman.ogg"
ffmpeg -i "/mnt/music/music/rocks/Van Halen - Discography @ 320/1988 OU812 (320)/02 - When It's Love.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - When It's Love.ogg"
ffmpeg -i "/mnt/music/music/rocks/WASP/1993 First Blood ... Last Cuts/15 - hold on to my heart.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/15 - hold on to my heart.ogg"
ffmpeg -i "/mnt/music/music/rocks/WASP/1998 The Crimson Idol 2xCD/(disc 1)/W.A.S.P - The Crimson Idol - 08 - The Idol.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/W.A.S.P - The Crimson Idol - 08 - The Idol.ogg"
ffmpeg -i "/mnt/music/music/rocks/Winger/1993 - Pull/03-Spell I'm Under.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03-Spell I'm Under.ogg"
ffmpeg -i "/mnt/music/music/rocks/Yngwie J. Malmsteen/1992 - Fire And Ice/11 - I'm My Own Enemy.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/11 - I'm My Own Enemy.ogg"
ffmpeg -i "/mnt/music/music/rocks/Yngwie J. Malmsteen/1997 - Facing The Animal/05 - Like An Angel.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 - Like An Angel.ogg"
ffmpeg -i "/mnt/music/music/rocks/ccr/Creedence Clearwater Revival - Cosmo's Factory/09 - Who'll Stop The Rain.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09 - Who'll Stop The Rain.ogg"
ffmpeg -i "/mnt/music/music/rocks/ccr/Creedence Clearwater Revival - Pendulum + Mardi Gras/(1970) CCR - Pendulum/04. Have You Ever Seen the Rain.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04. Have You Ever Seen the Rain.ogg"
ffmpeg -i "/mnt/music/music/rocks/ccr/Creedence Clearwater Revival - Pendulum + Mardi Gras/(1972) CCR - Mardi Gras/05. Someday Never Comes.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05. Someday Never Comes.ogg"
ffmpeg -i "/mnt/music/music/rocks/europe/1986 - The Final Countdown/01 The Final Countdown.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 The Final Countdown.ogg"
ffmpeg -i "/mnt/music/music/rocks/europe/1986 - The Final Countdown/03 Carrie.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/03 Carrie.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/07 - Nightwish - Sleeping Sun.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - Nightwish - Sleeping Sun.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/09.AXEL RUDI PELL - Heartbreaker.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/09.AXEL RUDI PELL - Heartbreaker.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/25 - Bonfire - Goodnight Amanda.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/25 - Bonfire - Goodnight Amanda.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/31 - Kreator - Golden Age.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/31 - Kreator - Golden Age.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/49 - Therion - The King.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/49 - Therion - The King.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/Moondance.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Moondance.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/Motorhead - Evolution.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Motorhead - Evolution.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/Rod Stewart - Sailing.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Rod Stewart - Sailing.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/Savatage - 1991 - Streets- A Rock Opera/Savatage - 1991 - Streets- A Rock Opera - 10 - New York City Don't Mean Nothing.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Savatage - 1991 - Streets- A Rock Opera - 10 - New York City Don't Mean Nothing.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/Sentenced---Killing Me Killing You.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Sentenced---Killing Me Killing You.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/SlowlyWeRot.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/SlowlyWeRot.ogg"
ffmpeg -i "/mnt/music/music/rocks/new colection/the phantom of opera.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/the phantom of opera.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1990] Cowboys From Hell/(01) [Pantera] Cowboys From Hell.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(01) [Pantera] Cowboys From Hell.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1990] Cowboys From Hell/(04) [Pantera] Heresy.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(04) [Pantera] Heresy.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1990] Cowboys From Hell/(05) [Pantera] Cemetery Gates.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(05) [Pantera] Cemetery Gates.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1992] Vulgar Display Of Power/(01) [Pantera] Mouth For War.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(01) [Pantera] Mouth For War.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1992] Vulgar Display Of Power/(02) [Pantera] A New Level.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(02) [Pantera] A New Level.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1992] Vulgar Display Of Power/(03) [Pantera] Walk.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(03) [Pantera] Walk.ogg"
ffmpeg -i "/mnt/music/music/rocks/pantera/[1992] Vulgar Display Of Power/(04) [Pantera] Fucking Hostile.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/(04) [Pantera] Fucking Hostile.ogg"
ffmpeg -i "/mnt/music/music/rocks/PINK_FLOYD_full_discography_FLAC-lossless_ZoneTeam/Wish you were here/Pink Floyd-Wish You Were Here-04-Wish You Were Here.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Pink Floyd-Wish You Were Here-04-Wish You Were Here.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Piece Of Mind/01 Where Eagles Dare.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 Where Eagles Dare.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/02 Rainmaker.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 Rainmaker.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/04 Monts_gur.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/04 Monts_gur.ogg"
ffmpeg -i "/mnt/music/music/rocks/Iron Maiden/Iron Maiden_Dance of Death/05 Dance Of Death.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Dance Of Death.ogg"
ffmpeg -i "/mnt/music/music/rocks/Deicide/Deicide - Serpents Of The Light (1997)/01 - Deicide - Serpents Of The Light.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Deicide - Serpents Of The Light.ogg"
ffmpeg -i "/mnt/music/music/rocks/Exodus/1985 - Bonded By Blood (320)/01 - Bonded By Blood.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Bonded By Blood.ogg"
ffmpeg -i "/mnt/music/music/rocks/Anthrax - Discography/1987 - Among The Living (320)/01 - Among The Living.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/01 - Among The Living.ogg"
ffmpeg -i "/mnt/music/music/rocks/Rainbow - discography/1979 - Down To Earth/05 Rainbow - Since You Been Gone.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05 Rainbow - Since You Been Gone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Exodus/1985 - Bonded By Blood (320)/02 - Exodus.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Exodus.ogg"
ffmpeg -i "/mnt/music/music/rocks/Anthrax - Discography/1990 - Persistence Of Time (320)/06 - Intro to Reality.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - Intro to Reality.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/The Gallery/Dark Tranquility - The Gallery - 10 - Mine Is The Grandeur....mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - The Gallery - 10 - Mine Is The Grandeur....ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Tranquility/The Gallery/Dark Tranquility - The Gallery - 04 - The gallery.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Dark Tranquility - The Gallery - 04 - The gallery.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death Angel/Act III/06 - A Room With a View.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 - A Room With a View.ogg"
ffmpeg -i "/mnt/music/music/rocks/Death Angel/The Ultra-Violence/05-The Ultra-Violence.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/05-The Ultra-Violence.ogg"
ffmpeg -i "/mnt/music/music/rocks/Venom/1981 - Welcome To Hell/02 - Welcome To Hell.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Welcome To Hell.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dream Theater/(2003) Train of Thought/06 Dream Theater - Stream of Consciousness.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/06 Dream Theater - Stream of Consciousness.ogg"
ffmpeg -i "/mnt/music/music/rocks/Van Halen - Discography @ 320/1978 Van Halen (320)/02 - Eruption.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/02 - Eruption.ogg"
ffmpeg -i "/mnt/music/music/rocks/collection/Heart - Alone.mp3" -acodec libvorbis -ab 192k "/mnt/music/music/rock/Heart - Alone.ogg"
ffmpeg -i "/mnt/music/music/rocks/Dark Moor/Dark Moor - The Hall Of The Olden Dreams/07 - THE SOUND OF THE BLADE.flac" -acodec libvorbis -ab 192k "/mnt/music/music/rock/07 - THE SOUND OF THE BLADE.ogg"
